version: '3.3'

services:
  web: 
    build: 
      context: ../SilentNotary-CilExplorer/
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
  cil-core:
    build: 
      context: ../Cil-core/
      dockerfile: Dockerfile
    ports:
     - "8222:8222"
     - "8223:8223"
    volumes: 
     - "/Users/runinterface/Desktop:/app/db"
    depends_on:
     - mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=yourStrong(!)Password
    ports:
     - "1434:1433"