version: '3.3'

services:
  web: 
    build: 
      context: ../SilentNotary-CilExplorer/
      dockerfile: Dockerfile.test
    ports:
     - "8081:8080"
  cil-core:
    build: 
      context: ../Cil-core/
      dockerfile: Dockerfile.test
    environment:
    - NODE_ENV=Devel
    - DEBUG=node:app, node:messages, node:messages:full
    ports:
     - "18222:18222"
     - "18223:18223"
    volumes: 
     - "/Users/runinterface/Desktop:/app/db"
    depends_on:
     - mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=yourStrong(!)Password
    ports:
     - "1433:1433"

