version: '3.3'

services:
  web: 
    build: 
      context: ../SilentNotary-CilExplorer/
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
  cil-core:
    build: 
      context: ../Cil-core/
      dockerfile: Dockerfile
    ports:
     - "8222:8222"
     - "8223:8223"
    volumes: 
     - "/Users/runinterface/Desktop:/app/db"

