version: '3.3'

services:
  webserver:
    build: 
      context: ../SilentNotary-CilExplorer/
      dockerfile: Dockerfile
    volumes: 
     - "../ubikiri-certs/:/etc/nginx/certs"
    ports:
     - "80:80"
     - "443:443"
    restart: always
  mssql-prod:
    build: 
      context: ../sql-server/
      dockerfile: Dockerfile

#Нужно указать путь до существующей папки с mssql
#    volumes: 
#     - "../mssqlDb/test:/var/opt/mssql"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=BhggG1z900
    ports:
     - "1433:1433"
    restart: always
  cil-core-prod:
    build: 
      context: ../Cil-core/
      dockerfile: Dockerfile
    environment:
    - DEBUG=node:app
    ports:
     - "8222:8222"
     - "8223:8223"
    depends_on:
     - mssql-prod
    restart: always
#    volumes: 
#     - "../levelDb/prod:/app/db"
  cil-storage-prod:
    build: 
      context: ../Cil-Storage/
      dockerfile: Dockerfile
#    ports:
#     - "7000:80"
    depends_on:
     - mssql-prod
    restart: always
