version: '3.3'

services:
  webserver:
    build: 
      context: ../SilentNotary-CilExplorer/
      dockerfile: Dockerfile
    volumes: 
     - "../ubikiri-certs/:/etc/nginx/certs"
    ports:
     - "80:80"
     - "443:443"
    restart: always
  mssql-test:
    build: 
      context: ../sql-server/
      dockerfile: Dockerfile

#Нужно указать путь до существующей папки с mssql
#    volumes: 
#     - "../mssqlDb/test:/var/opt/mssql"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=BhggG1z900
    ports:
     - "1434:1433"
    restart: always
    container_name: app_cil-webserver_1
  cil-core-test:
    build: 
      context: ../Cil-core/
      dockerfile: Dockerfile.test
    environment:
    - NODE_ENV=Devel
    - DEBUG=node:app, node:messages, node:messages:full
    ports:
     - "18222:18222"
     - "18223:18223"
    depends_on:
     - mssql-test
    restart: always
#    volumes: 
#     - "../levelDb/test:/app/db"
  cil-storage-test:
    build: 
      context: ../Cil-Storage/
      dockerfile: Dockerfile.test
#    ports:
#     - "7001:80"
    depends_on:
     - mssql-test
    restart: always
