version: '3.3'

services:
  webserver:
    image: "nginx:latest"
#Нужно указать путь до nginx config
#    volumes: 
#     - "/path/to/nginx_conf:/etc/nginx/"
    ports:
     - "80:80"
     - "443:443"
    restart: always
  web: 
    build: 
      context: ../SilentNotary-CilExplorer/
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    restart: always
  mssql:
    image: "mcr.microsoft.com/mssql/server:latest"
#Нужно указать путь до существующей папки с mssql
#    volumes: 
#     - "/path/to/mssqldb_prod:/var/opt/mssql"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=yourStrong(!)Password
    ports:
     - "1434:1433"
    restart: always
  cil-core:
    build: 
      context: ../Cil-core/
      dockerfile: Dockerfile
    ports:
     - "8222:8222"
     - "8223:8223"
    restart: always
# Нужно указать путь до существующей папки с данными от leveldb
#    volumes: 
#     - "/path/to/leveldb_prod:/app/db"
    depends_on:
     - mssql
  cil-storage:
    build: 
    context: ../Cil-Storage/
    dockerfile: Dockerfile.test
# Нужно указать путь до рабочего appsettings.json
#    volumes: 
#     - "/Users/runinterface/Desktop/appsettings.json:/app/appsettings.json"
    ports:
     - "7000:80"
    depends_on:
     - mssql
    restart: always
